cmake_minimum_required(VERSION 3.15...4.0)

project(goblin VERSION "0.1.0")

set(CMAKE_CXX_STANDARD 23)
# -std=c++xx instead of -std=g++xx
set(CMAKE_CXX_EXTENSIONS OFF)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")

# provide the shared dependencies
add_subdirectory(extern)

option(GOBLIN_BUILD_TESTING "Build the test targets" ON)
option(GOBLIN_BUILD_DOCS "Build the docs" ON)
option(GOBLIN_BUILD_PYLIB "Build the Python bindings" OFF)

include(CTest)

# enable ccache if available
find_program(CCACHE_PROGRAM ccache)
if(CCACHE_PROGRAM)
    set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
    set(CMAKE_CUDA_COMPILER_LAUNCHER "${CCACHE_PROGRAM}") # CMake 3.9+
endif()

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "" FORCE)
endif()

if (CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    set(
        CMAKE_CXX_FLAGS_DEBUG
        "${CMAKE_CXX_FLAGS_DEBUG} -Wall -Werror -Wpedantic -Wnon-virtual-dtor -Woverloaded-virtual -g -fsanitize=undefined -fsanitize=address"
    )
    set(
        CMAKE_CXX_FLAGS_RELEASE
        "${CMAKE_CXX_FLAGS_RELEASE} -Wall -Werror -O3 -march=native"
        )
endif()

# -flto (link time optimization)
# include(CheckIPOSupported)
# check_ipo_supported(RESULT ipo_supported OUTPUT error)
# if(ipo_supported)
#     set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
#     set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO TRUE)
# endif()

add_subdirectory(lib)

if(SKBUILD OR GOBLIN_BUILD_PYLIB)
    include(cmake/litgen_cmake.cmake)

    litgen_find_nanobind()
    set(python_module_sources
        pylib/nanobind/module.cpp                  # The python module entry point
        pylib/nanobind/bindings.cpp        # The bindings to the library, which are mainly auto-generated by litgen
    )

    # This will output a dynamic library called for example:
    #     _pygoblin.cpython-312-darwin.so on macOS
    #     _pygoblin.cpython-312-x86_64-linux-gnu.so on Linux
    #     _pygoblin.cp312-win_amd64.pyd on Windows)
    nanobind_add_module(_pygoblin ${python_module_sources})

    litgen_setup_module(
        # The C++ library for which we are building bindings
        lib
        # The native python module name
        _pygoblin
        # This is the python wrapper around the native module
        pygom
        # The path where the python module will be copied after build (for editable mode)
        ${CMAKE_CURRENT_SOURCE_DIR}/pylib/pygom
    )

    find_package(Eigen3 REQUIRED)           # Eigen3::Eigen
    find_package(OpenRAND REQUIRED)         # OpenRAND::OpenRAND
    find_package(gomea_library REQUIRED)    # gomea_library
    target_link_libraries(_pygoblin
        PRIVATE
            Eigen3::Eigen
            OpenRAND::OpenRAND
            gomea_library
    )
endif()
