[project]
name = "revisiting-linkage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "baycomp>=1.0.3",
    "click>=8.1.8",
    "duckdb>=1.3.2",
    "matplotlib>=3.5.3",
    "networkx>=2.6.3",
    "numpy>=1.21.6",
    "pandas>=1.1.5",
    "pmlb>=1.0.1.post3",
    "pygom",
    "pystan>=3.4.0",
    "pyyaml>=6.0.1",
    "rliable>=1.2.0",
    "scikit-learn>=1.0.2",
    "scipy>=1.7.3",
    "seaborn>=0.12.2",
    "sympy>=1.10.1",
    "tqdm>=4.67.1",
    "ucimlrepo>=0.0.7",
]

[tool.uv.sources]
pygom = { path = "../../../" }
