#include <iostream>
#include "doctest/doctest.h"
#include <Eigen/Dense>

#include "goblin/bench/functions/discrete.h"
#include "goblin/bench/problem.h"
#include "goblin/lib/linkage.h"
#include "goblin/lib/misc.h"

// using namespace std::chrono_literals;
using namespace goblin;

TEST_CASE("goblin::lib::entropy") {
  BenchmarkInstance instance(std::make_shared<OneMax>(4));
  AoSSet solutions;
  Rng rng = seeded_rng(42);
  instance.add_random(rng, solutions, 8);
  std::vector<usize> indices{0, 1, 2, 3};

  std::vector<usize> subset{0, 1, 2, 3};

  solutions[0].discrete_values() << 0, 0, 1, 1;
  solutions[1].discrete_values() << 1, 1, 0, 0;
  solutions[2].discrete_values() << 1, 1, 1, 1;
  solutions[3].discrete_values() << 0, 0, 0, 0;

  auto H = estimate_entropy(instance, solutions, indices, subset,
                            /* intron_strategy = */ "none",
                            /* merge_continuous = */ false,
                            /* num_continuous_bins = */ std::nullopt);

  for (isize i = 0; i < H.rows(); i++) {
    for (isize j = 0; j < H.cols(); j++) {
      std::print("{:>4.2f},", H(i, j));
    }
    std::println("");
  }

  REQUIRE(H(0, 0) == 1.0);
  REQUIRE(H(1, 1) == 1.0);
  REQUIRE(H(2, 2) == 1.0);
  REQUIRE(H(3, 3) == 1.0);

  REQUIRE(H(0, 1) == 1.0);
  REQUIRE(H(1, 0) == 1.0);

  REQUIRE(H(2, 3) == 1.0);
  REQUIRE(H(3, 2) == 1.0);

  REQUIRE(H(0, 2) == 2.0);
  REQUIRE(H(0, 3) == 2.0);
  REQUIRE(H(1, 2) == 2.0);
  REQUIRE(H(1, 3) == 2.0);

  // introns
  solutions[0].discrete_values() << 1, 1, 0, 1;
  solutions[1].discrete_values() << 1, 0, 1, 0;
  solutions[2].discrete_values() << 1, 1, 0, 1;
  solutions[3].discrete_values() << 0, 1, 1, 0;

  solutions[0].discrete_active() << 1, 0, 1, 1;
  solutions[1].discrete_active() << 1, 0, 0, 0;
  solutions[2].discrete_active() << 1, 0, 1, 1;
  solutions[3].discrete_active() << 1, 1, 0, 0;

  H = estimate_entropy(instance, solutions, indices, subset,
                       /* intron_strategy = */ "none",
                       /* merge_continuous = */ false,
                       /* num_continuous_bins = */ std::nullopt);
  auto H_ia = estimate_entropy(instance, solutions, indices, subset,
                               /* intron_strategy = */ "any_active",
                               /* merge_continuous = */ false,
                               /* num_continuous_bins = */ std::nullopt);
  auto H_aa = estimate_entropy(instance, solutions, indices, subset,
                               /* intron_strategy = */ "all_active",
                               /* merge_continuous = */ false,
                               /* num_continuous_bins = */ std::nullopt);
  auto H_mo = estimate_entropy(instance, solutions, indices, subset,
                               /* intron_strategy = */ "mark_only",
                               /* merge_continuous = */ false,
                               /* num_continuous_bins = */ std::nullopt);

  std::println("");
  for (isize i = 0; i < H.rows(); i++) {
    for (isize j = 0; j < H.cols(); j++) {
      std::print("{:>4.2f},", H(i, j));
    }
    std::println("");
  }
  std::println("H any active");
  for (isize i = 0; i < H_ia.rows(); i++) {
    for (isize j = 0; j < H_ia.cols(); j++) {
      std::print("{:>4.2f},", H_ia(i, j));
    }
    std::println("");
  }

  std::println("H all active");
  for (isize i = 0; i < H_aa.rows(); i++) {
    for (isize j = 0; j < H_aa.cols(); j++) {
      std::print("{:>4.2f},", H_aa(i, j));
    }
    std::println("");
  }

  std::println("H mask only");
  for (isize i = 0; i < H_mo.rows(); i++) {
    for (isize j = 0; j < H_mo.cols(); j++) {
      std::print("{:>4.2f},", H_mo(i, j));
    }
    std::println("");
  }

  // REQUIRE(false);
};

// This test case is autogenerated by sampling values and comparing to a reference implementation
// - ask Johannes Koch for more info if needed
TEST_CASE("goblin::lib::entropy_any_active") {
  BenchmarkInstance instance(std::make_shared<OneMax>(4));
  AoSSet solutions;
  Rng rng = seeded_rng(42);
  instance.add_random(rng, solutions, 8);
  std::vector<usize> indices{0, 1, 2, 3, 4, 5, 6, 7};
  std::vector<usize> subset{0, 1, 2, 3};

  auto check = [](const Mat<CType>& actual, const Mat<CType>& expected, usize sample) {
    REQUIRE(actual.rows() == expected.rows());
    REQUIRE(actual.cols() == expected.cols());

    std::println("actual:");
    for (isize i = 0; i < actual.rows(); i++) {
      for (isize j = 0; j < actual.cols(); j++) {
        std::print("{:>4.2f},", actual(i, j));
      }
      std::println("");
    }

    std::println("expected:");
    for (isize i = 0; i < expected.rows(); i++) {
      for (isize j = 0; j < expected.cols(); j++) {
        std::print("{:>4.2f},", expected(i, j));
      }
      std::println("");
    }

    for (isize i = 0; i < expected.rows(); i++) {
      for (isize j = 0; j < expected.cols(); j++) {
        REQUIRE_MESSAGE(actual(i, j) == doctest::Approx(expected(i, j)), "Sample: ", sample, ", H(", i, ", ", j, ")");
      }
    }
  };

  Mat<CType> H;
  Mat<CType> H_expected(4, 4);

  // Sample 0
  solutions[0].discrete_values() << 0, 1, 1, 0;
  solutions[1].discrete_values() << 0, 1, 0, 1;
  solutions[2].discrete_values() << 0, 0, 1, 1;
  solutions[3].discrete_values() << 1, 1, 1, 1;
  solutions[4].discrete_values() << 1, 0, 1, 0;
  solutions[5].discrete_values() << 1, 0, 0, 1;
  solutions[6].discrete_values() << 1, 1, 0, 1;
  solutions[7].discrete_values() << 1, 0, 0, 0;

  solutions[0].discrete_active() << 0, 1, 1, 0;
  solutions[1].discrete_active() << 1, 1, 0, 1;
  solutions[2].discrete_active() << 0, 1, 1, 0;
  solutions[3].discrete_active() << 0, 1, 0, 1;
  solutions[4].discrete_active() << 1, 1, 1, 0;
  solutions[5].discrete_active() << 0, 0, 0, 0;
  solutions[6].discrete_active() << 1, 0, 1, 1;
  solutions[7].discrete_active() << 1, 1, 0, 1;

  H = estimate_entropy(instance, solutions, indices, subset,
                       /* intron_strategy = */ "any_active",
                       /* merge_continuous = */ false,
                       /* num_continuous_bins = */ std::nullopt);

  H_expected << 0.81127812, 2.23592635, 2.25162917, 2.32192809, 2.23592635, 1.00000000, 2.23592635, 2.23592635,
      2.25162917, 2.23592635, 0.81127812, 1.84237099, 2.32192809, 2.23592635, 1.84237099, 0.81127812;

  check(H, H_expected, 0);

  // Sample 1
  solutions[0].discrete_values() << 0, 0, 1, 0;
  solutions[1].discrete_values() << 0, 0, 1, 0;
  solutions[2].discrete_values() << 0, 0, 1, 0;
  solutions[3].discrete_values() << 0, 0, 1, 1;
  solutions[4].discrete_values() << 1, 0, 0, 1;
  solutions[5].discrete_values() << 1, 1, 0, 0;
  solutions[6].discrete_values() << 1, 1, 0, 1;
  solutions[7].discrete_values() << 1, 0, 1, 0;

  solutions[0].discrete_active() << 0, 1, 1, 0;
  solutions[1].discrete_active() << 1, 0, 1, 0;
  solutions[2].discrete_active() << 1, 1, 1, 1;
  solutions[3].discrete_active() << 0, 1, 0, 1;
  solutions[4].discrete_active() << 1, 0, 1, 1;
  solutions[5].discrete_active() << 0, 0, 0, 0;
  solutions[6].discrete_active() << 0, 1, 1, 0;
  solutions[7].discrete_active() << 1, 1, 0, 1;

  H = estimate_entropy(instance, solutions, indices, subset,
                       /* intron_strategy = */ "any_active",
                       /* merge_continuous = */ false,
                       /* num_continuous_bins = */ std::nullopt);

  H_expected << 1.00000000, 2.52164064, 2.25162917, 2.32192809, 2.52164064, 0.72192809, 2.23592635, 2.25162917,
      2.25162917, 2.23592635, 0.97095059, 2.52164064, 2.32192809, 2.25162917, 2.52164064, 1.00000000;

  check(H, H_expected, 1);

  // Sample 2
  solutions[0].discrete_values() << 1, 1, 1, 1;
  solutions[1].discrete_values() << 0, 1, 1, 0;
  solutions[2].discrete_values() << 1, 0, 0, 0;
  solutions[3].discrete_values() << 1, 0, 0, 0;
  solutions[4].discrete_values() << 1, 1, 0, 0;
  solutions[5].discrete_values() << 1, 0, 1, 0;
  solutions[6].discrete_values() << 1, 0, 0, 1;
  solutions[7].discrete_values() << 0, 1, 1, 1;

  solutions[0].discrete_active() << 1, 1, 0, 0;
  solutions[1].discrete_active() << 0, 1, 0, 0;
  solutions[2].discrete_active() << 0, 0, 0, 0;
  solutions[3].discrete_active() << 1, 1, 1, 0;
  solutions[4].discrete_active() << 1, 0, 1, 1;
  solutions[5].discrete_active() << 1, 0, 0, 1;
  solutions[6].discrete_active() << 0, 0, 0, 0;
  solutions[7].discrete_active() << 0, 0, 1, 1;

  H = estimate_entropy(instance, solutions, indices, subset,
                       /* intron_strategy = */ "any_active",
                       /* merge_continuous = */ false,
                       /* num_continuous_bins = */ std::nullopt);

  H_expected << 0.00000000, 1.92192809, 1.52192809, 1.52192809, 1.92192809, 0.91829583, 1.92192809, 1.91829583,
      1.52192809, 1.92192809, 0.91829583, 2.00000000, 1.52192809, 1.91829583, 2.00000000, 0.91829583;

  check(H, H_expected, 2);

  // Sample 3
  solutions[0].discrete_values() << 1, 0, 1, 0;
  solutions[1].discrete_values() << 0, 0, 0, 1;
  solutions[2].discrete_values() << 0, 1, 0, 1;
  solutions[3].discrete_values() << 0, 0, 1, 1;
  solutions[4].discrete_values() << 0, 1, 0, 1;
  solutions[5].discrete_values() << 1, 0, 1, 0;
  solutions[6].discrete_values() << 0, 0, 0, 1;
  solutions[7].discrete_values() << 0, 0, 1, 0;

  solutions[0].discrete_active() << 1, 0, 1, 1;
  solutions[1].discrete_active() << 1, 0, 0, 1;
  solutions[2].discrete_active() << 0, 1, 0, 1;
  solutions[3].discrete_active() << 1, 0, 0, 1;
  solutions[4].discrete_active() << 0, 1, 0, 1;
  solutions[5].discrete_active() << 1, 0, 1, 0;
  solutions[6].discrete_active() << 1, 0, 0, 0;
  solutions[7].discrete_active() << 0, 0, 1, 0;

  H = estimate_entropy(instance, solutions, indices, subset,
                       /* intron_strategy = */ "any_active",
                       /* merge_continuous = */ false,
                       /* num_continuous_bins = */ std::nullopt);

  H_expected << 0.97095059, 1.55665671, 1.45914792, 2.23592635, 1.55665671, 0.00000000, 0.97095059, 1.52192809,
      1.45914792, 0.97095059, 0.00000000, 1.37878349, 2.23592635, 1.52192809, 1.37878349, 0.72192809;

  check(H, H_expected, 3);
};
